### ISSUE TITLE
pytorch 1.0以上 自带ctc ，这个源码要怎样改一下吗？谢谢

### ISSUE THREAD

**Issue by QQ2737499951** [airaria/CaptchaRecognition#5]
pytorch 1.0以上 自带ctc ，这个源码要怎样改一下吗？谢谢

**Comment by airaria** [comment]
> pytorch 1.0以上 自带ctc ，这个源码要怎样改一下吗？谢谢

那就用不着装 warp_ctc了。
pytorch自带的ctc我还没看过。
我有空改一下吧，目前这个版本也是比较老了
